# Change these first
owner: op-xyz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: App
    url: https://api.op.xyz/core/v0/health
  - name: Minter
    url: https://api.op.xyz/v1/health/blockchain
  - name: API
    url: https://api.op.xyz/v1/health

  # - name: Mainnet Indexer
  #   url: https://api.op.xyz/v1/health/blockchain/mainnet
  # - name: Apechain Indexer
  #   url: https://api.op.xyz/v1/health/blockchain/apechain
  # - name: Base Indexer
  #   url: https://api.op.xyz/v1/health/blockchain/base
  # - name: Polygon Indexer
  #   url: https://api.op.xyz/v1/health/blockchain/polygon
  # - name: Curtis Indexer
  #   url: https://api.op.xyz/v1/health/blockchain/curtis

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.op.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.op.xyz/icon.png
  themeUrl: https://status.op.xyz/theme.css
  name: op.xyz
  introTitle: Status
  introMessage: 
  navbar:
    # - title: Status
    #   href: /
    # - title: GitHub
    #   href: https://github.com/cr3labs/other-page-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
